# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathon Henderson
tagline: Software Engineer
email: your-email@example.com
description: >-
  A software engineer and consultant based near Newcastle upon Tyne with a passion for
  backend development using Kotlin, Java, Rust and Go.
url: https://jonathonhenderson.co.uk # the base hostname & protocol for your site, e.g. http://example.com
default_author: Jonathon

social_icons:
  github: https://github.com/jrhenderson1988
  linkedin: https://www.linkedin.com/in/jrhenderson1988
  twitter: https://www.twitter.com/jrhenderson1988
  stackoverflow: https://stackoverflow.com/users/2244675/jonathon

show_exerpts: true
total_recent_posts: 3
professional_beginning_year: 2011
beginning_year: 2004


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
